services:

    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: blog
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017

    mongo-gui:
        build:
            context: .
            dockerfile: mongo-gui.dockerfile
        restart: always
        depends_on:
            - mongodb
        environment:
            - MONGO_URL=mongodb://user:password@mongodb:27017
        ports:
            - 4321:4321